# Generated by Django 2.2 on 2019-06-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='brunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='rehearsal_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='shabbat',
            field=models.BooleanField(default=False),
        ),
    ]
