# Generated by Django 2.2 on 2019-04-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190417_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='invited',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
