# Generated by Django 2.2 on 2019-07-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_guest_wedding_rehearsal'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_attending_brunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_attending_rehearsal_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_attending_shabbat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_attending_wedding_rehearsal',
            field=models.BooleanField(default=False),
        ),
    ]
