# Generated by Django 2.2 on 2019-07-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190704_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fancy_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
