# Generated by Django 2.2 on 2019-04-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190417_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
