# Generated by Django 2.2 on 2019-07-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_event_fancy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='has_responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='has_responded_brunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='has_responded_rehearsal_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='has_responded_shabbat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='has_responded_wedding_rehearsal',
            field=models.BooleanField(default=False),
        ),
    ]
